# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: load-testing
  labels:
    name: load-testing
    app.kubernetes.io/name: load-testing
    security.policy.io/isolation: test-environment

---
# ConfigMap für Load Test App
apiVersion: v1
kind: ConfigMap
metadata:
  name: load-test-config
  namespace: load-testing
data:
  PORT: "8080"
  HOST: "0.0.0.0"
  FLASK_ENV: "production"
  LOG_LEVEL: "INFO"
  ECHO_SERVICE_URL: "http://vulnerable-echo-service:8085"

---
# ConfigMap für Vulnerable Echo Service
apiVersion: v1
kind: ConfigMap
metadata:
  name: vulnerable-echo-config
  namespace: load-testing
data:
  SERVER_PORT: "8085"
  JAVA_OPTS: "-Xmx512m -Xms256m -Dlog4j.configurationFile=/app/log4j2.xml"
  LOG4J_FORMAT_MSG_NO_LOOKUPS: "false"  # VULNERABLE
  LOG4J2_DISABLE_JNDI: "false"  # VULNERABLE

---
# Secret für potenzielle Credentials (demo)
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: load-testing
type: Opaque
data:
  # Base64 kodierte Demo-Credentials
  database-user: bG9hZHRlc3Q=      # loadtest
  database-password: cGFzc3dvcmQ=  # password
  api-key: dGVzdC1hcGkta2V5        # test-api-key

---
# Deployment für Load Test App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-app
  namespace: load-testing
  labels:
    app: load-test-app
    version: v2.0.0
    component: frontend
    tier: web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: load-test-app
  template:
    metadata:
      labels:
        app: load-test-app
        version: v2.0.0
        component: frontend
        tier: web
      annotations:
        # Monitoring Annotations
        instana.io/monitored: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        # Security Annotations
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        # Deployment Info
        kubectl.kubernetes.io/default-container: load-test-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      
      containers:
      - name: load-test-app
        image: mbx1010/load-test-app:2.0
        imagePullPolicy: Always
        
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        
        # Environment Variablen
        envFrom:
        - configMapRef:
            name: load-test-config
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        
        # Resource Limits
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "512Mi"
            cpu: "1000m"
            ephemeral-storage: "2Gi"
        
        # Health Checks
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        
        # Startup Probe
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
        
        # Security Context
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        
        # Volume Mounts
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: cache-volume
          mountPath: /app/cache
      
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: cache-volume
        emptyDir: {}
      
      # Node Selection
      nodeSelector:
        kubernetes.io/os: linux

---
# Deployment für Vulnerable Echo Service (ohne PVC)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-echo-service
  namespace: load-testing
  labels:
    app: vulnerable-echo-service
    version: v1.0.0-vulnerable
    component: backend
    tier: api
    vulnerability: log4j-cve-2021-44228
spec:
  replicas: 1  # Nur eine Replica für vulnerable service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: vulnerable-echo-service
  template:
    metadata:
      labels:
        app: vulnerable-echo-service
        version: v1.0.0-vulnerable
        component: backend
        tier: api
        vulnerability: log4j-cve-2021-44228
      annotations:
        # Monitoring Annotations
        instana.io/monitored: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        prometheus.io/path: "/actuator/prometheus"
        # Vulnerability Annotations
        vulnerability.scanner.io/ignore: "false"
        security.policy.io/profile: "test-only"
        security.vulnerability.io/cve: "CVE-2021-44228"
        # Deployment Info
        kubectl.kubernetes.io/default-container: vulnerable-echo-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      
      containers:
      - name: vulnerable-echo-service
        image: mbx1010/vulnerable-echo-service:latest
        imagePullPolicy: Always
        
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
        - containerPort: 8080
          name: management
          protocol: TCP
        
        # Environment Variablen
        envFrom:
        - configMapRef:
            name: vulnerable-echo-config
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SPRING_PROFILES_ACTIVE
          value: "production,vulnerable"
        
        # Resource Limits
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "1000m"
            ephemeral-storage: "3Gi"
        
        # Health Checks
        livenessProbe:
          httpGet:
            path: /health
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        # Startup Probe
        startupProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 15
        
        # Volume Mounts - EmptyDir für Logs
        volumeMounts:
        - name: log-volume
          mountPath: /app/logs
        - name: tmp-volume
          mountPath: /tmp
        
        # Security Context (weniger restriktiv für vulnerable service)
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
      
      volumes:
      - name: log-volume
        emptyDir:
          sizeLimit: 1Gi
      - name: tmp-volume
        emptyDir: {}

---
# Service für Load Test App
apiVersion: v1
kind: Service
metadata:
  name: load-test-service
  namespace: load-testing
  labels:
    app: load-test-app
    component: frontend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: load-test-app

---
# Service für Vulnerable Echo Service
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-echo-service
  namespace: load-testing
  labels:
    app: vulnerable-echo-service
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/actuator/prometheus"
    service.vulnerability.io/status: "vulnerable"
    service.vulnerability.io/cve: "CVE-2021-44228"
spec:
  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: management
  selector:
    app: vulnerable-echo-service

---
# LoadBalancer Service für externen Zugriff
apiVersion: v1
kind: Service
metadata:
  name: load-test-loadbalancer
  namespace: load-testing
  labels:
    app: load-test-app
    service-type: loadbalancer
  annotations:
    # MetalLB Annotations (falls verwendet)
    service.kubernetes.io/load-balancer-source-ranges: "0.0.0.0/0"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: load-test-app

---
# Komplette Ingress Konfiguration ersetzen

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: load-test-ingress
  namespace: load-testing
  labels:
    app: load-test-ingress
    component: routing
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # Load Test App API Routen (WICHTIG!)
      - path: /stress
        pathType: Exact
        backend:
          service:
            name: load-test-service
            port:
              number: 80
      - path: /echo
        pathType: Exact
        backend:
          service:
            name: load-test-service
            port:
              number: 80
      - path: /stop
        pathType: Exact
        backend:
          service:
            name: load-test-service
            port:
              number: 80
      - path: /health
        pathType: Exact
        backend:
          service:
            name: load-test-service
            port:
              number: 80
      - path: /metrics
        pathType: Exact
        backend:
          service:
            name: load-test-service
            port:
              number: 80
      - path: /status
        pathType: Exact
        backend:
          service:
            name: load-test-service
            port:
              number: 80
      
      # Echo Service direkte API
      - path: /api/echo
        pathType: Prefix
        backend:
          service:
            name: vulnerable-echo-service
            port:
              number: 8085
      
      # Default - Load Test App
      - path: /
        pathType: Prefix
        backend:
          service:
            name: load-test-service
            port:
              number: 80

---
# HorizontalPodAutoscaler für Load Test App
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: load-test-hpa
  namespace: load-testing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-test-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
